### ISSUE TITLE
HTTP Verb Error 1704

### ISSUE THREAD

**Issue by habibihhustla** [kdoronzio/fmREST.php#10]
Hey there, I am using your fmRest API since a while and everything works great thanks! However, when I try to use findRecords, I always get this error: Resource doesn't support the specified HTTP verb [code] => 1704

I tried debugging it, looked at your fmrest.php file and so on but never found out what's wrong..

Do you have any idea concerning this topic? 

Kind regards
Yassin

**Comment by mbcbus** [comment]
Please post a snippet of sample code of the query you are trying to make, otherwise it's incredibly difficult for anyone to assist in troubleshooting.

**Comment by habibihhustla** [comment]
@mbcbus you are right, sorry for that, here is a snippet of the findRecords code:

include_once('fmREST.php');

$fm = new fmREST();
$fm->host = 'xy.xyz.com';
$fm->db = 'X.fmp12';
$fm->user = 'username';
$fm->pass = 'password';

$layout = 'X';

$date = new DateTime('NOW');
$date = $date->format('Y-m-d H:i:s');
$timestamp = strtotime($date);
$request1['typ'] = '0';
$query = array($request1);
$data['query'] = $query;
$data['limit'] = 1;

$result = $fm->findRecords($data);

**Comment by mbcbus** [comment]
Is your **X::typ** field a number or text field? You are casting zero to a string in your find request which might matter for accurate results.

Also, is the **X::typ** field on the $layout you are setting to perform the find?

What version of filemaker server?

What's the output of **$fm -> show_debug = true;** if you add this after your call: **print_r ($fm->debug_array);**

Have you tried another example call that isn't layout/find specific? Such as: **$result = $fm -> layoutNames ();** to confirm the Data API is working properly?

Also, your DB name includes the **".fmp12"** extension, which I do not believe is needed.

**Comment by habibihhustla** [comment]
**X::typ** is a number and it is shown in the layout.

The Filemaker server runs with the version: 18.0.3.319 

The output is: 
Array ( [login start cookie] => Array ( [fmtoken] => [Phpstorm-x] => X [_ga] => X ) [login existing token] => X [Succeeded initial login] => Array ( [response] => Array ( [token] => X) [messages] => Array ( [0] => Array ( [code] => 0 [message] => Already have a token. ) ) ) [pre-payload: ] => Array ( [query] => Array ( [0] => Array ( [typ] => 0 ) ) [limit] => 1 ) [not empty token on call] => X [payload: ] => Array ( [query] => Array ( [0] => Array ( [typ] => 0 ) ) [limit] => 1 ) [header] => Array ( [0] => Authorization:Bearer X [1] => Content-Type: application/json ) [url] => https://x.x.com/fmi/data/vLatest/databases/X.fmp12/layouts//_find [call error: ] => [call result: ] => {"messages":[{"message":"Resource doesn't support the specified HTTP verb","code":"1704"}],"response":{}} [call info: ] => Array ( [url] => https:// https://x.x.com/fmi/data/vLatest/databases/X.fmp12/layouts//_find [content_type] => application/json [http_code] => 405 [header_size] => 333 [request_size] => 245 [filetime] => -1 [ssl_verify_result] => 0 [redirect_count] => 0 [total_time] => 0.081742 [namelookup_time] => 0.019166 [connect_time] => 0.026888 [pretransfer_time] => 0.071603 [size_upload] => 33 [size_download] => 105 [speed_download] => 1296 [speed_upload] => 407 [download_content_length] => -1 [upload_content_length] => 33 [starttransfer_time] => 0.071611 [redirect_time] => 0 [redirect_url] => [primary_ip] => xxx.xxx.xx.xx [certinfo] => Array ( ) [primary_port] => xxx [local_ip] => xxx.xxx.x.xxx [local_port] => xxxxxx [http_version] => 3 [protocol] => 2 [ssl_verifyresult] => 0 [scheme] => HTTPS [appconnect_time_us] => 71390 [connect_time_us] => 26888 [namelookup_time_us] => 19166 [pretransfer_time_us] => 71603 [redirect_time_us] => 0 [starttransfer_time_us] => 71611 [total_time_us] => 81742 ) [findRecords pass 1] => Array ( [messages] => Array ( [0] => Array ( [message] => Resource doesn't support the specified HTTP verb [code] => 1704 ) ) [response] => Array ( ) ) [login result] => Array ( [response] => Array ( [token] => X ) [messages] => Array ( [0] => Array ( [code] => 0 [message] => OK ) ) ) [login end cookie] => Array ( [fmtoken] => X [Phpstorm-x] => X [_ga] => X ) [checkValidResult] => 2nd login succeeded [findRecords pass 2] => Array ( [messages] => Array ( [0] => Array ( [message] => Resource doesn't support the specified HTTP verb [code] => 1704 ) ) [response] => Array ( ) ) )

Yes I have tried it with createRecord, which is working.

**Comment by mbcbus** [comment]
In the URL you show a double slash after "layouts" which would indicate $layout might be null.

You can review starting at line 294: 
https://github.com/kdoronzio/fmREST.php/blob/master/fmREST.php
To see how the layout is used to put together the url used in the query.

You haven't modified fmREST.php at all correct?

**Comment by mbcbus** [comment]
Look at sample.php lines 11-17 versus your code making the connection to FM.
https://github.com/kdoronzio/fmREST.php/blob/master/sample.php

```
$host = 'myhost.domain.com';
$db = 'fmREST-sample';
$user = 'fmrest';
$pass = 'paradise';
$layout = 'sample';

$fm = new fmREST ($host, $db, $user, $pass, $layout);
```

In the sample, $layout is being passed when creating the new object. In your code though, you are setting $layout as a variable without actually using it anywhere.

So in essence, the function in fmREST.php reverts back to the objects default value (set on creation), unless you specifically pass in a $layout argument to the findRecords() method.

You can either adapt your connection code to match the sample above, or just actually USE your $layout variable in the function:
```
$result = $fm->findRecords($data, $layout);
```

I'm guessing this is your issue, which was identified by seeing that layout was missing from your URL (although I realize you're masking your url, so I can't be sure).

**Comment by habibihhustla** [comment]
Thank you so much @mbcbus for your invested time and great explaining! I just tried it out and it works now, the http verb error is gone :) cheers mate 👍
