### ISSUE TITLE
Error : HTTP/2 stream 0 was not closed cleanly

### ISSUE THREAD

**Issue by SaumonFume** [kdoronzio/fmREST.php#12]
First, Many thanks for your tool. I'm not a developper and I can simply use it for data publication from FM on a website. 
But, since few days, I've this error when I open the connection to FM with fmrest  : 
Result: HTTP/2 stream 0 was not closed cleanly: Unknown error code (err 1)

For the moment, I have solved the problem, thanks to an info on StackOverflow, by adding this line (on line 384):
curl_setopt ($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
(Be careful, I don't know if this is the right thing to do).

(https://stackoverflow.com/questions/56865217/php-curl-error-http-2-stream-0-was-not-closed-cleanly-protocol-error-err-1)

Best Regards,

**Comment by kdoronzio** [comment]
Thank you for this. I looked into it, and indeed this seems to be an issue with the latest version of FileMaker Server 19.3. 

We'll be updating this code shortly.

**Comment by kdoronzio** [comment]
Thanks for this. You actually helped answer a client question.

And you prompted an update to the class, which is now online.

Thanks
Ken


---------------------------------
Ken d'Oronzio
Paradise Partners, Inc.
866-999-4006 x201
