### ISSUE TITLE
Sorting Example

### ISSUE THREAD

**Issue by marksprofm** [kdoronzio/fmREST.php#13]
There seems to be no examples for Sorting the found records.

**Comment by kdoronzio** [comment]
Hi Mark - 

We follow the [Data API structure](https://fmhelp.filemaker.com/docs/18/en/dataapi/index.html#write-fm-data-api-calls_perform-a-find-request) for all of the functions. So to add a sort order to a find request, you would have to add a "sort" record to your query before running it. 

An example query might look like this:
```
{
  "query":[
    {"Group": "=Surgeon"},
    {"Work State" : "NY", "omit" : "true"}],
  "sort":[
    {"fieldName": "Work State","sortOrder": "ascend"},
    {"fieldName": "First Name", "sortOrder": "ascend"} ]
}
```

In PHP, it might look like (there are more optimized way to write this, but for sake of clarity...):
```
	//find records
	$request1['Text1'] = $_REQUEST['Text1'];
	$query = array ($request1);
	$data['query'] = $query;
	
	$sort1['fieldName']= "my field name";
	$sort1['sortOrder'] = 'ascend';
	$sort2['fieldName']= "my second sort field";
	$sort2['sortOrder'] = 'ascend';
	$sort = array ($sort1, $sort2);
	$data['sort'] = $sort;

	$result = $fm -> findRecords ($data); 

```

**Comment by kdoronzio** [comment]
Added a couple of examples to the sample file.
