### ISSUE TITLE
For use with webhooks

### ISSUE THREAD

**Issue by ChrisSLT** [kdoronzio/fmREST.php#6]
Hi,

Thanks for this great php class.  I've tweaked it to work with webhooks wherein it stores the session token to a text file on the server rather than a variable in the client's browser (since there wouldn't be a browser session in the case of webhooks).  

I've tested and it works, but others may have improvements.

I'm new to Github - is this something you'd like me to post or share back to this repository in some way?

Chris

**Comment by kdoronzio** [comment]
Chris.
Thanks.

I believe you can post it to the project. I'm not sure if you need to be
signed in as a contributor it not. If you prefer, it can't work out GitHub,
you can email the changes to me.

Thanks for offering.

Ken

**Comment by ChrisSLT** [comment]
Thanks Ken, here it is.


[fmRESTx.txt](https://github.com/kdoronzio/fmREST.php/files/3175086/fmRESTx.txt)

**Comment by kdoronzio** [comment]
I didn't roll it into this revision because we were focusing on FM18 updates. I like the idea of having the option to store token information elsewhere. I need to roll this feature in carefully, though, to make sure that it can be turned on & off by the developer, without breaking the default cookie feature.

**Comment by ChrisSLT** [comment]
Great

For Filemaker 18, are they still forcing us to get a token?  It seems
inefficient for a webhook to have to make that many calls

**Comment by kdoronzio** [comment]
Yes, tokens are how FM Data API maintains security.



---------------------------------
Ken d'Oronzio
Paradise Partners, Inc.
866-999-4006 x201

**Comment by ChrisSLT** [comment]
Yes, however I tend to see options in most other apis to be able to avoid
token exchange for strictly server-side workflows.  Hopefully one day with
FM.

Hope all is well, again, many thanks for the clarity/simplicity of your
class, and let me know if I can help in any way.

**Comment by kdoronzio** [comment]
Our api wrapper certainly helps with that - in fact that's one of the
reasons we created it - so you just pass the user name and password, and
leave the token up to the api.

I noticed in one of the edits you made (I think to "createRecord") that you
commented out the login() line. That's fundamental to how the script works
- it handles all the logins automatically and stores the token for you. By
commenting out that step, you stop the auto-login feature.

---------------------------------
Ken d'Oronzio
Paradise Partners, Inc.
866-999-4006 x201

**Comment by ChrisSLT** [comment]
Hi - yes, I commented it out only because of storing the token in a text
file.  All the login function does is check for the existing of a token.
Since after the first time it's used, there will always be a token in the
text file, it seemed redundant.  I think you're doing something cooler with
storing it in a cookie, because it will automatically unset the token after
15 minutes, thus making auto login helpful.  Wish there were some way to do
that in a text file?

**Comment by kdoronzio** [comment]
Incorporating session storage in latest build, upcoming...
