### ISSUE TITLE
Parameters in documentation are off

### ISSUE THREAD

**Issue by theUgluk** [kdoronzio/fmREST.php#8]
First of all I wanted to thank you for this great piece of code. It did save me a lot of headaches.

I notices there's a difference in the parameters the [Filemaker Data API ](https://fmhelp.filemaker.com/docs/18/en/dataapi/#work-with-records_get-records)expects and the examples you provided. For the `getRecords` function you mention the `offset` and `range` parameters, but the FM API expects `_offset` and `_limit`.
Any change this can be edited?

**Comment by kdoronzio** [comment]
This must have been updated a while ago. Just closing the issue.
